name: Build and Deploy to github packages
on:
  schedule:
  - cron: 0 0 * * * #JSTで9時
  push:

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest Releases
        id: releases
        run: |
          ref=`curl -s https://api.github.com/repos/misskey-dev/misskey/releases/latest | jq -r '.tag_name'` &&
          echo '::set-output name=REF::$ref'
      - name: Checkout
        uses: actions/checkout@v2
        with:
            repository: misskey-dev/misskey
            ref: '${{ steps.releases.outputs.REF }}'
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/misskey-arm64:latest
            ghcr.io/${{ github.repository_owner }}/misskey-arm64:${{ github.event.inputs.target }}
          cache-from: type=registry,ref=user/app:latest
          cache-to: type=inline

